swagger: "2.0"
info:
  description: "This is a sample API."
  version: "3.0.0"
  title: "Events API"
host: "events.example.com"
basePath: "/v3"
tags:
- name: "events"
  description: "Everything about events"
  externalDocs:
    description: "Find out more"
    url: "http://events.examle"
- name: "categories"
  description: "Event categories"
  externalDocs:
    description: "Find out more"
    url: "http://events.examle"
schemes:
- "http"
paths:
  /events:
    post:
      tags:
      - "events"
      summary: "Add a new event to the events"
      description: ""
      operationId: "addEvent"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Event object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Event"
      responses:
        "405":
          description: "Invalid input"
    put:
      tags:
      - "events"
      summary: "Update an existing event"
      description: ""
      operationId: "updateEvent"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Event object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Event"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Event not found"
        "405":
          description: "Validation exception"
    get:
      tags:
      - "events"
      summary: "Get all events"
      description: ""
      operationId: "getAllEvent"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
  /events/{eventId}:
    get:
        tags:
        - "events"
        summary: "Find events by ID"
        description: "Return a single event"
        operationId: "findEventsById"
        produces:
        - "application/json"
        parameters:
        - name: "eventId"
          in: "path"
          description: "ID of event"
          required: true
          type: "integer"
          format: "int64"
        responses:
          "200":
            description: "successful operation"
            schema:
              $ref: "#/definitions/Event"
          "400":
            description: "Invalid ID supplied"
          "404":
            description: "Event not found"
    delete:
      tags:
        - "events"
      summary: "Delete event"
      description: ""
      operationId: "deleteEvent"
      produces:
      - "application/json"
      parameters:
      - name: "eventId"
        in: "path"
        description: "Event ID to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
  /events/findByTitle:
    get:
      tags:
      - "events"
      summary: "Find events by title"
      description: ""
      operationId: "findEventsByTitle"
      produces:
      - "application/json"
      parameters:
      - name: "title"
        in: "query"
        description: "Event title"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
        "400":
          description: "Invalid title value"
  /categories:
    post:
        tags:
        - "categories"
        summary: "Add a new category to the categories"
        description: ""
        operationId: "addCategory"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - in: "body"
          name: "body"
          description: "Category object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Category"
        responses:
          "405":
            description: "Invalid input"
    get:
      tags:
      - "categories"
      summary: "Get all categories"
      description: ""
      operationId: "getAllCategories"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Category"
definitions:
  Event:
    type: "object"
    required:
    - "title"
    - "status"
    - "date"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        example: "BRING ME THE HORIZON"
      status:
        type: "string"
        description: "event status"
        enum:
        - "await"
        - "passed"
      price:
        type: "integer"
        format: "int32"
      category:
        $ref: "#/definitions/Category"
      date:
        type: "string"
        format: "date"
      description:
        type: "string"
  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        example: "Concert"