openapi: 3.0.3
info:
  description: "This is a sample API."
  version: 3.0.0
  title: "Events API"
servers:
  - url: http://localhost/api/v3
tags:
  - name: "events"
    description: "Everything about events"
  - name: "categories"
    description: "Event categories"
paths:
  /events:
    post:
      tags:
        - "events"
      summary: "Add a new event to the events"
      description: ""
      operationId: "addEvent"
      requestBody:
        description: "Event object that needs to be added"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventRequest"
      responses:
        '201':
          description: "Created"
        "405":
          description: "Invalid input"
    get:
      tags:
        - "events"
      summary: "Get all events"
      description: ""
      operationId: "getAllEvent"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/EventModel"
  /events/{eventId}:
    get:
      tags:
        - "events"
      summary: "Find events by ID"
      description: "Return a single event"
      operationId: "findEventsById"
      parameters:
        - name: "eventId"
          in: "path"
          description: "ID of event"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventModel"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Event not found"
    delete:
      tags:
        - "events"
      summary: "Delete event"
      description: ""
      operationId: "deleteEvent"
      parameters:
        - name: "eventId"
          in: "path"
          description: "Event ID to delete"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "201":
          description: operation successful
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Event not found"
  /events/findByTitle:
    get:
      tags:
        - "events"
      summary: "Find events by title"
      description: ""
      operationId: "findEventsByTitle"
      parameters:
        - name: "title"
          in: "query"
          description: "Event title"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/EventModel"
        "400":
          description: "Invalid title value"
  /categories:
    post:
      tags:
        - "categories"
      summary: "Add a new category to the categories"
      description: ""
      operationId: "addCategory"
      requestBody:
        description: "Category object that needs to be added"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryModel"
      responses:
        "201":
          description: "category added"
        "405":
          description: "Invalid input"
    get:
      tags:
        - "categories"
      summary: "Get all categories"
      description: ""
      operationId: "getAllCategories"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/CategoryModel"
  /categories/{categoryId}:
    delete:
      tags:
        - categories
      summary: Delete event
      description: ''
      operationId: deleteCategory
      parameters:
        - name: categoryId
          in: path
          description: Category ID to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "201":
          description: operation successful
        '400':
          description: Invalid ID supplied
        '404':
          description: Category not found

components:
  schemas:
    EventRequest:
      type: "object"
      required:
        - "title"
        - "status"
        - "date"
      properties:
        title:
          type: "string"
          example: "BRING ME THE HORIZON"
        price:
          type: "integer"
          format: "int32"
        category_id:
          type: "integer"
          format: "int64"
        date:
          type: "string"
          format: "date"
        description:
          type: "string"
    EventModel:
      type: "object"
      required:
        - "title"
        - "status"
        - "date"
      properties:
        id:
          type: "integer"
          format: "int64"
          readOnly: true
        title:
          type: "string"
          example: "BRING ME THE HORIZON"
        price:
          type: "integer"
          format: "int32"
        category:
          $ref: "#/components/schemas/CategoryModel"
        date:
          type: "string"
          format: "date"
        description:
          type: "string"
    CategoryModel:
      type: "object"
      required:
        - "title"
      properties:
        id:
          type: "integer"
          format: "int64"
          readOnly: true
        title:
          type: "string"
          example: "Concert"
